"""Worker-only structured template adapter; paths are generated by the Worker, not browser inputs."""
import json
import os
import sys


def execute(path):
    from pipesim_template_preflight import toolkit_runtime
    from pipesim_template_profile import run_template_profile
    from ptk_normalization import normalize_profile
    with open(path, encoding="utf-8-sig") as source:
        request = json.load(source)
    if set(request) != {"well", "inputs", "output"}:
        raise ValueError("Invalid internal creation request")
    with toolkit_runtime(os.environ["PIPESIM_PTK_PATH"]):
        import sixgill.definitions as definitions
        from sixgill.pipesim import Model
        return run_template_profile(Model, definitions, request["output"], request["well"], request["inputs"], normalize_profile)


if __name__ == "__main__":
    try:
        # No imports that could launch the engine before the process-tree job is assigned.
        if os.environ.get("GRDP_PTK_START_GATED") == "1" and json.loads(sys.stdin.readline()) != {"type": "start"}:
            raise ValueError("Adapter start gate was not released")
        response = execute(sys.argv[1])
    except Exception as error:
        import traceback
        traceback.print_exc(file=sys.stderr)
        response = {"schemaVersion": "pipesim-template-profile-preflight/1", "calculationVerified": False,
                    "adapterError": type(error).__name__, "modelDiagnostics": []}
    print(json.dumps(response, ensure_ascii=False, allow_nan=False))
